# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: quarterly
      timezone: "Asia/Ho_Chi_Minh"
    assignees:
      - "Herve-M"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      timezone: "Asia/Ho_Chi_Minh"
    assignees:
      - "Herve-M"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: quarterly
      timezone: "Asia/Ho_Chi_Minh"
    assignees:
      - "Herve-M"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Ho_Chi_Minh"
    assignees:
      - "Herve-M"
    commit-message:
      prefix: "chore(deps)"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      aspire:
        patterns:
          - "Aspire.*"
          - "CommunityToolkit.Aspire.*"
      opentelemetry:
        patterns:
          - "OpenTelemetry.*"
      modelcontextprotocol:
        patterns:
          - "ModelContextProtocol.*"
      httpApi:
        patterns:
          - "Scalar.*"
          - "Asp.Versioning.*"
      dotnetdiag:
        patterns:
          - "DotNetDiag.*"
      fluentvalidation:
        patterns:
          - "FluentValidation.*"
      mediator:
        patterns:
          - "Mediator.*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
