name: server-mcp-pr

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths-ignore:
      - src/Server.Api/**
      - .devcontainer/**
      - .vscode/**
      - .idea/**
      - docs/**
      - README.md

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-slim

    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v6.0.2

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v5.3.0
        with:
          dotnet-version: 10.0.x

      #TODO: find a up to date dotnet format action that supports recent updates
      # - name: "dotnet format"
      #   uses: jfversluis/dotnet-format@v1.0.9
      #   with:
      #     action: check
      #     only-changed-files: true
      #     fail-fast: true
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Dependency review"
        uses: actions/dependency-review-action@v5
        with:
          license-check: true
          vulnerability-check: true
          comment-summary-in-pr: on-failure

      - name: "Restore tools"
        run: dotnet tool restore

      - name: "Restore dependencies"
        run: dotnet restore

      - name: "Build server-mcp (win-x64)"
        run: dotnet build src/Server.Mcp/Server.Mcp.csproj --configuration Release --no-restore --runtime win-x64

      - name: "Build server-mcp (win-arm64)"
        run: dotnet build src/Server.Mcp/Server.Mcp.csproj --configuration Release --no-restore --runtime win-arm64

      - name: "Build server-mcp (osx-arm64)"
        run: dotnet build src/Server.Mcp/Server.Mcp.csproj --configuration Release --no-restore --runtime osx-arm64

      - name: "Build server-mcp (linux-x64)"
        run: dotnet build src/Server.Mcp/Server.Mcp.csproj --configuration Release --no-restore --runtime linux-x64

      - name: "Build server-mcp (linux-arm64)"
        run: dotnet build src/Server.Mcp/Server.Mcp.csproj --configuration Release --no-restore --runtime linux-arm64

      - name: "Pack server-mcp"
        run: dotnet pack src/Server.Mcp/Server.Mcp.csproj --configuration Release --no-build --no-restore -o ${{ runner.temp }}
